### ISSUE TITLE
An API incompatibility was encountered while executing net.alchim31.maven:scala-maven-plugin:4.0.1

### ISSUE THREAD

**Issue by gridcellcoder** [davidB/scala-maven-plugin#336]
Hello There

Were using 

```
 <scala.version>2.12</scala.version>
 <scala.minor.version>2.12.0</scala.minor.version>
```

Maven
```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T19:41:47+01:00)
Maven home: /home/xyz/tools/maven/apache-maven-3.6.0
**Java version: 1.8.0_212, vendor: Eclipse OpenJ9, runtime: /home/xyz/tools/java/jdk8u212-b03/jre**
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-18-generic", arch: "amd64", family: "unix"
```
and have
```
<dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scala.minor.version}</version>
            <scope>compile</scope>
        </dependency>
```

and 
```
<plugin>
                <groupId>net.alchim31.maven</groupId>
                <artifactId>scala-maven-plugin</artifactId>
                <version>4.0.1</version>
                <executions>
                    <!--https://github.com/davidB/scala-maven-plugin/issues/234-->
                        <execution>
                            <id>scala-compile-first</id>
                            <phase>compile</phase>
                            <goals>
                                <goal>add-source</goal>
                                <goal>compile</goal>
                            </goals>
                        </execution>
                    <execution>
                        <id>scala-test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

and maven compiler
```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

but a simple `mvn clean compile` results in 
```
ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.0.1:compile (scala-compile-first) on project client: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.0.1:compile failed: An API incompatibility was encountered while executing net.alchim31.maven:scala-maven-plugin:4.0.1:compile: java.lang.IncompatibleClassChangeError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>net.alchim31.maven:scala-maven-plugin:4.0.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/xyz/.m2/repository/net/alchim31/maven/scala-maven-plugin/4.0.1/scala-maven-plugin-4.0.1.jar
[ERROR] urls[1] = file:/home/xyz/.m2/repository/org/apache/maven/maven-builder-support/3.3.9/maven-builder-support-3.3.9.jar
[ERROR] urls[2] = file:/home/xyz/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar
[ERROR] urls[3] = file:/home/xyz/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
[ERROR] urls[4] = file:/home/xyz/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[5] = file:/home/xyz/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.2/org.eclipse.sisu.inject-0.3.2.jar
[ERROR] urls[6] = file:/home/xyz/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.6/plexus-component-annotations-1.6.jar
[ERROR] urls[7] = file:/home/xyz/.m2/repository/org/apache/maven/reporting/maven-reporting-api/3.0/maven-reporting-api-3.0.jar
[ERROR] urls[8] = file:/home/xyz/.m2/repository/org/eclipse/aether/aether-util/1.0.2.v20150114/aether-util-1.0.2.v20150114.jar
[ERROR] urls[9] = file:/home/xyz/.m2/repository/com/google/inject/guice/4.0/guice-4.0-no_aop.jar
[ERROR] urls[10] = file:/home/xyz/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[11] = file:/home/xyz/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[12] = file:/home/xyz/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[13] = file:/home/xyz/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
[ERROR] urls[14] = file:/home/xyz/.m2/repository/org/apache/maven/shared/maven-dependency-tree/3.0.1/maven-dependency-tree-3.0.1.jar
[ERROR] urls[15] = file:/home/xyz/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar
[ERROR] urls[16] = file:/home/xyz/.m2/repository/org/codehaus/plexus/plexus-utils/3.1.1/plexus-utils-3.1.1.jar
[ERROR] urls[17] = file:/home/xyz/.m2/repository/org/codehaus/plexus/plexus-archiver/4.1.0/plexus-archiver-4.1.0.jar
[ERROR] urls[18] = file:/home/xyz/.m2/repository/org/codehaus/plexus/plexus-io/3.1.1/plexus-io-3.1.1.jar
[ERROR] urls[19] = file:/home/xyz/.m2/repository/org/apache/commons/commons-compress/1.18/commons-compress-1.18.jar
[ERROR] urls[20] = file:/home/xyz/.m2/repository/org/iq80/snappy/snappy/0.4/snappy-0.4.jar
[ERROR] urls[21] = file:/home/xyz/.m2/repository/org/tukaani/xz/1.8/xz-1.8.jar
[ERROR] urls[22] = file:/home/xyz/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[23] = file:/home/xyz/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[24] = file:/home/xyz/.m2/repository/org/apache/maven/maven-archiver/3.4.0/maven-archiver-3.4.0.jar
[ERROR] urls[25] = file:/home/xyz/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.jar
[ERROR] urls[26] = file:/home/xyz/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
[ERROR] urls[27] = file:/home/xyz/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.8/doxia-sink-api-1.8.jar
[ERROR] urls[28] = file:/home/xyz/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.8/doxia-logging-api-1.8.jar
[ERROR] urls[29] = file:/home/xyz/.m2/repository/org/apache/maven/shared/maven-invoker/3.0.1/maven-invoker-3.0.1.jar
[ERROR] urls[30] = file:/home/xyz/.m2/repository/org/scala-sbt/zinc_2.12/1.2.5/zinc_2.12-1.2.5.jar
[ERROR] urls[31] = file:/home/xyz/.m2/repository/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6.jar
[ERROR] urls[32] = file:/home/xyz/.m2/repository/org/scala-sbt/zinc-core_2.12/1.2.5/zinc-core_2.12-1.2.5.jar
[ERROR] urls[33] = file:/home/xyz/.m2/repository/org/scala-sbt/zinc-apiinfo_2.12/1.2.5/zinc-apiinfo_2.12-1.2.5.jar
[ERROR] urls[34] = file:/home/xyz/.m2/repository/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.jar
[ERROR] urls[35] = file:/home/xyz/.m2/repository/org/scala-sbt/zinc-classpath_2.12/1.2.5/zinc-classpath_2.12-1.2.5.jar
[ERROR] urls[36] = file:/home/xyz/.m2/repository/org/scala-lang/scala-compiler/2.12.6/scala-compiler-2.12.6.jar
[ERROR] urls[37] = file:/home/xyz/.m2/repository/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.jar
[ERROR] urls[38] = file:/home/xyz/.m2/repository/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.jar
[ERROR] urls[39] = file:/home/xyz/.m2/repository/org/scala-sbt/io_2.12/1.2.0/io_2.12-1.2.0.jar
[ERROR] urls[40] = file:/home/xyz/.m2/repository/com/swoval/apple-file-events/1.3.2/apple-file-events-1.3.2.jar
[ERROR] urls[41] = file:/home/xyz/.m2/repository/net/java/dev/jna/jna/4.5.0/jna-4.5.0.jar
[ERROR] urls[42] = file:/home/xyz/.m2/repository/net/java/dev/jna/jna-platform/4.5.0/jna-platform-4.5.0.jar
[ERROR] urls[43] = file:/home/xyz/.m2/repository/org/scala-sbt/util-logging_2.12/1.2.2/util-logging_2.12-1.2.2.jar
[ERROR] urls[44] = file:/home/xyz/.m2/repository/com/eed3si9n/sjson-new-core_2.12/0.8.2/sjson-new-core_2.12-0.8.2.jar
[ERROR] urls[45] = file:/home/xyz/.m2/repository/jline/jline/2.14.4/jline-2.14.4.jar
[ERROR] urls[46] = file:/home/xyz/.m2/repository/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
[ERROR] urls[47] = file:/home/xyz/.m2/repository/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
[ERROR] urls[48] = file:/home/xyz/.m2/repository/com/lmax/disruptor/3.3.6/disruptor-3.3.6.jar
[ERROR] urls[49] = file:/home/xyz/.m2/repository/com/eed3si9n/sjson-new-scalajson_2.12/0.8.2/sjson-new-scalajson_2.12-0.8.2.jar
[ERROR] urls[50] = file:/home/xyz/.m2/repository/com/eed3si9n/shaded-scalajson_2.12/1.0.0-M4/shaded-scalajson_2.12-1.0.0-M4.jar
[ERROR] urls[51] = file:/home/xyz/.m2/repository/org/spire-math/jawn-parser_2.12/0.10.4/jawn-parser_2.12-0.10.4.jar
[ERROR] urls[52] = file:/home/xyz/.m2/repository/org/scala-lang/scala-reflect/2.12.6/scala-reflect-2.12.6.jar
[ERROR] urls[53] = file:/home/xyz/.m2/repository/org/scala-sbt/util-relation_2.12/1.2.2/util-relation_2.12-1.2.2.jar
[ERROR] urls[54] = file:/home/xyz/.m2/repository/org/scala-sbt/zinc-persist_2.12/1.2.5/zinc-persist_2.12-1.2.5.jar
[ERROR] urls[55] = file:/home/xyz/.m2/repository/com/trueaccord/scalapb/scalapb-runtime_2.12/0.6.0/scalapb-runtime_2.12-0.6.0.jar
[ERROR] urls[56] = file:/home/xyz/.m2/repository/com/trueaccord/lenses/lenses_2.12/0.4.12/lenses_2.12-0.4.12.jar
[ERROR] urls[57] = file:/home/xyz/.m2/repository/com/lihaoyi/fastparse_2.12/0.4.2/fastparse_2.12-0.4.2.jar
[ERROR] urls[58] = file:/home/xyz/.m2/repository/com/lihaoyi/fastparse-utils_2.12/0.4.2/fastparse-utils_2.12-0.4.2.jar
[ERROR] urls[59] = file:/home/xyz/.m2/repository/com/lihaoyi/sourcecode_2.12/0.1.3/sourcecode_2.12-0.1.3.jar
[ERROR] urls[60] = file:/home/xyz/.m2/repository/com/google/protobuf/protobuf-java/3.3.1/protobuf-java-3.3.1.jar
[ERROR] urls[61] = file:/home/xyz/.m2/repository/org/scala-sbt/sbinary_2.12/0.5.0/sbinary_2.12-0.5.0.jar
[ERROR] urls[62] = file:/home/xyz/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar
[ERROR] urls[63] = file:/home/xyz/.m2/repository/org/scala-sbt/zinc-compile-core_2.12/1.2.5/zinc-compile-core_2.12-1.2.5.jar
[ERROR] urls[64] = file:/home/xyz/.m2/repository/org/scala-sbt/launcher-interface/1.0.0/launcher-interface-1.0.0.jar
[ERROR] urls[65] = file:/home/xyz/.m2/repository/org/scala-lang/modules/scala-parser-combinators_2.12/1.0.5/scala-parser-combinators_2.12-1.0.5.jar
[ERROR] urls[66] = file:/home/xyz/.m2/repository/org/scala-sbt/util-control_2.12/1.2.2/util-control_2.12-1.2.2.jar
[ERROR] urls[67] = file:/home/xyz/.m2/repository/org/scala-sbt/zinc-classfile_2.12/1.2.5/zinc-classfile_2.12-1.2.5.jar
[ERROR] urls[68] = file:/home/xyz/.m2/repository/org/scala-sbt/zinc-ivy-integration_2.12/1.2.5/zinc-ivy-integration_2.12-1.2.5.jar
[ERROR] urls[69] = file:/home/xyz/.m2/repository/org/scala-sbt/librarymanagement-core_2.12/1.2.0/librarymanagement-core_2.12-1.2.0.jar
[ERROR] urls[70] = file:/home/xyz/.m2/repository/com/jcraft/jsch/0.1.54/jsch-0.1.54.jar
[ERROR] urls[71] = file:/home/xyz/.m2/repository/com/eed3si9n/gigahorse-okhttp_2.12/0.3.0/gigahorse-okhttp_2.12-0.3.0.jar
[ERROR] urls[72] = file:/home/xyz/.m2/repository/com/eed3si9n/gigahorse-core_2.12/0.3.0/gigahorse-core_2.12-0.3.0.jar
[ERROR] urls[73] = file:/home/xyz/.m2/repository/com/typesafe/ssl-config-core_2.12/0.2.2/ssl-config-core_2.12-0.2.2.jar
[ERROR] urls[74] = file:/home/xyz/.m2/repository/com/typesafe/config/1.2.0/config-1.2.0.jar
[ERROR] urls[75] = file:/home/xyz/.m2/repository/org/reactivestreams/reactive-streams/1.0.0/reactive-streams-1.0.0.jar
[ERROR] urls[76] = file:/home/xyz/.m2/repository/com/squareup/okhttp3/okhttp/3.7.0/okhttp-3.7.0.jar
[ERROR] urls[77] = file:/home/xyz/.m2/repository/com/squareup/okio/okio/1.12.0/okio-1.12.0.jar
[ERROR] urls[78] = file:/home/xyz/.m2/repository/com/squareup/okhttp3/okhttp-urlconnection/3.7.0/okhttp-urlconnection-3.7.0.jar
[ERROR] urls[79] = file:/home/xyz/.m2/repository/org/scala-sbt/util-position_2.12/1.2.0/util-position_2.12-1.2.0.jar
[ERROR] urls[80] = file:/home/xyz/.m2/repository/org/scala-sbt/util-cache_2.12/1.2.0/util-cache_2.12-1.2.0.jar
[ERROR] urls[81] = file:/home/xyz/.m2/repository/com/eed3si9n/sjson-new-murmurhash_2.12/0.8.2/sjson-new-murmurhash_2.12-0.8.2.jar
[ERROR] urls[82] = file:/home/xyz/.m2/repository/org/scala-lang/modules/scala-java8-compat_2.12/0.9.0/scala-java8-compat_2.12-0.9.0.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```
and

`Ubuntu 18.10 4.18.0-18-generic`

Does this have to do with using adoptJDK https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9?

Or is this some other bug? Happy to provide more info to help debug this.

**Comment by gridcellcoder** [comment]
Same issue with 1.8 source and target
```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
                <executions>
                    <execution> 
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by slandelle** [comment]
Please push on github a sample project that reproduces your issue.

**Comment by gridcellcoder** [comment]
I created a minimum project which did not report the error but in my current project the full stack trace is below I think related to xsbt so I will try and debug that for now and will comment here.
```
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:184)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.IncompatibleClassChangeError
    at java.lang.StringBuilder.append (StringBuilder.java:2189)
    at xsbt.ClassName.$anonfun$classNameAsSeenIn$1 (ClassName.scala:83)
    at xsbt.ClassName$$Lambda$1298.00000000BB169B20.apply (Unknown Source)
    at scala.reflect.internal.SymbolTable.enteringPhase (SymbolTable.scala:235)
    at xsbt.ClassName.classNameAsSeenIn (ClassName.scala:78)
    at xsbt.ClassName.classNameAsSeenIn$ (ClassName.scala:76)
    at xsbt.ExtractAPI.classNameAsSeenIn (ExtractAPI.scala:49)
    at xsbt.ExtractAPI.mkClassLike (ExtractAPI.scala:666)
    at xsbt.ExtractAPI.$anonfun$classLike$1 (ExtractAPI.scala:649)
    at xsbt.ExtractAPI$$Lambda$1296.00000000BB1686D0.apply (Unknown Source)
    at scala.collection.mutable.AbstractMap.getOrElseUpdate (Map.scala:80)
    at xsbt.ExtractAPI.classLike (ExtractAPI.scala:649)
    at xsbt.ExtractAPI.extractAllClassesOf (ExtractAPI.scala:634)
    at xsbt.API$TopLevelHandler.class (API.scala:74)
    at xsbt.API$TopLevelTraverser.traverse (API.scala:82)
    at xsbt.API$TopLevelTraverser.traverse (API.scala:78)
    at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$2 (Trees.scala:2498)
    at scala.reflect.api.Trees$Traverser$$Lambda$498.00000000BACC3D60.apply$mcV$sp (Unknown Source)
    at scala.reflect.api.Trees$Traverser.atOwner (Trees.scala:2507)
    at scala.reflect.api.Trees$Traverser.$anonfun$traverseStats$1 (Trees.scala:2498)
    at scala.reflect.api.Trees$Traverser.traverseStats (Trees.scala:2497)
    at scala.reflect.internal.Trees.itraverse (Trees.scala:1330)
    at scala.reflect.internal.Trees.itraverse$ (Trees.scala:1204)
    at scala.reflect.internal.SymbolTable.itraverse (SymbolTable.scala:16)
    at scala.reflect.internal.SymbolTable.itraverse (SymbolTable.scala:16)
    at scala.reflect.api.Trees$Traverser.traverse (Trees.scala:2475)
    at xsbt.API$TopLevelTraverser.traverse (API.scala:84)
    at xsbt.API$TopLevelTraverser.traverse (API.scala:78)
    at scala.reflect.api.Trees$Traverser.apply (Trees.scala:2513)
    at xsbt.API$ApiPhase.processScalaUnit (API.scala:43)
    at xsbt.API$ApiPhase.processUnit (API.scala:35)
    at xsbt.API$ApiPhase.apply (API.scala:33)
    at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1 (Global.scala:402)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase (Global.scala:395)
    at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1 (Global.scala:366)
    at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted (Global.scala:366)
    at scala.tools.nsc.Global$GlobalPhase$$Lambda$485.00000000BAC9C9F0.apply (Unknown Source)
    at scala.collection.AbstractIterator.foreach (Iterator.scala:932)
    at scala.tools.nsc.Global$GlobalPhase.run (Global.scala:366)
    at xsbt.API$ApiPhase.run (API.scala:27)
    at scala.tools.nsc.Global$Run.compileUnitsInternal (Global.scala:1404)
    at scala.tools.nsc.Global$Run.compileUnits (Global.scala:1389)
    at scala.tools.nsc.Global$Run.compileSources (Global.scala:1384)
    at scala.tools.nsc.Global$Run.compile (Global.scala:1478)
    at xsbt.CachedCompiler0.run (CompilerInterface.scala:130)
    at xsbt.CachedCompiler0.run (CompilerInterface.scala:105)
    at xsbt.CompilerInterface.run (CompilerInterface.scala:31)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at sbt.internal.inc.AnalyzingCompiler.call (AnalyzingCompiler.scala:237)
    at sbt.internal.inc.AnalyzingCompiler.compile (AnalyzingCompiler.scala:111)
    at sbt.internal.inc.AnalyzingCompiler.compile (AnalyzingCompiler.scala:90)
    at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3 (MixedAnalyzingCompiler.scala:82)
    at sbt.internal.inc.MixedAnalyzingCompiler$$Lambda$208.00000000B9F3FCE0.apply$mcV$sp (Unknown Source)
    at scala.runtime.java8.JFunction0$mcV$sp.apply (JFunction0$mcV$sp.java:12)
    at sbt.internal.inc.MixedAnalyzingCompiler.timed (MixedAnalyzingCompiler.scala:133)
    at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1 (MixedAnalyzingCompiler.scala:73)
    at sbt.internal.inc.MixedAnalyzingCompiler.compile (MixedAnalyzingCompiler.scala:116)
    at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1 (IncrementalCompilerImpl.scala:307)
    at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted (IncrementalCompilerImpl.scala:307)
    at sbt.internal.inc.IncrementalCompilerImpl$$Lambda$149.00000000B93E8CB0.apply (Unknown Source)
    at sbt.internal.inc.Incremental$.doCompile (Incremental.scala:106)
    at sbt.internal.inc.Incremental$.$anonfun$compile$4 (Incremental.scala:87)
    at sbt.internal.inc.Incremental$$$Lambda$189.00000000B920CB60.apply (Unknown Source)
    at sbt.internal.inc.IncrementalCommon.recompileClasses (IncrementalCommon.scala:116)
    at sbt.internal.inc.IncrementalCommon.cycle (IncrementalCommon.scala:63)
    at sbt.internal.inc.Incremental$.$anonfun$compile$3 (Incremental.scala:89)
    at sbt.internal.inc.Incremental$$$Lambda$187.00000000B920B700.apply (Unknown Source)
    at sbt.internal.inc.Incremental$.manageClassfiles (Incremental.scala:134)
    at sbt.internal.inc.Incremental$.compile (Incremental.scala:80)
    at sbt.internal.inc.IncrementalCompile$.apply (Compile.scala:67)
    at sbt.internal.inc.IncrementalCompilerImpl.compileInternal (IncrementalCompilerImpl.scala:311)
    at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1 (IncrementalCompilerImpl.scala:269)
    at sbt.internal.inc.IncrementalCompilerImpl$$Lambda$47.00000000B9CCB5E0.apply (Unknown Source)
    at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError (IncrementalCompilerImpl.scala:159)
    at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally (IncrementalCompilerImpl.scala:238)
    at sbt.internal.inc.IncrementalCompilerImpl.compile (IncrementalCompilerImpl.scala:69)
    at sbt_inc.SbtIncrementalCompiler.compile (SbtIncrementalCompiler.java:127)
    at scala_maven.ScalaCompilerSupport.incrementalCompile (ScalaCompilerSupport.java:282)
    at scala_maven.ScalaCompilerSupport.compile (ScalaCompilerSupport.java:100)
    at scala_maven.ScalaCompilerSupport.doExecute (ScalaCompilerSupport.java:83)
    at scala_maven.ScalaMojoSupport.execute (ScalaMojoSupport.java:554)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
```

**Comment by slandelle** [comment]
Caused by: java.lang.IncompatibleClassChangeError
    at java.lang.StringBuilder.append (StringBuilder.java:2189)

This is super weird. This means that the StringBuilder version you have in your JDK is different from the one sbt was compiled against o_O
Are you trying to run a custom JDK or a custom java.lang.StringBuilder?

**Comment by gridcellcoder** [comment]
That's a possibility , I am using adoptJDK https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9? and this seems to be the main issue, I did not have sbt installed when I first ran this so still trying to figure out how this is all conflicting with each other, I might start a new VM in the cloud with a fresh in stall of everything to see whats causing the issue.

**Comment by slandelle** [comment]
Why are you using J9???
J9 is a proprietary JVM that IBM finally open sourced last year.
It’s supposed to be compliant to the Java spec but who knows...
Could you please try regular Hotspot instead?

**Comment by gridcellcoder** [comment]
Same issue with Hotspot, we're trying out J9 as its now supported by eclipse and there are some blogs that suggest it works better in docker...so just testing i out.

 The issue is related to xsbt so have raised it there https://github.com/sbt/zinc/issues/665 but have also created a minimum project https://github.com/gridcellcoder/scala-xbt-debug

**Comment by slandelle** [comment]
No idea why scala-maven-plugin interprets `<scala.version>2.12</scala.version>` as `2.12.0` (that's a question for @davidB :P).

Anyway, this looks like an issue with early Scala versions. The issue goes away if you upgrade to 2.12.8.

```
<scala.version>2.12.8</scala.version>
<scala.minor.version>2.12.8</scala.minor.version>
```

Then, I have no idea why you both specify `scala.version` and explicitly pull `scala-library` dependency. You probably should drop `scala.version`.

Side question for @davidB : what is this `scala.version` property for anyway? Why would someone use this instead of pulling dep?

**Comment by gridcellcoder** [comment]
Sometimes I use scala.version like this

```
 <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_${scala.version}</artifactId>
            <version>${spark.version}</version>
        </dependency>
```

and minor version like this 
```
<dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>${scala.minor.version}</version>
            <!--<scope>compile</scope>-->
        </dependency>
```

This seems to fix it
```
  <scala.version>2.12.8</scala.version>
        <scala.minor.version>2.12.8</scala.minor.version>
```

Thanks for the help!

**Comment by davidB** [comment]
`scala.version` is used to define scala version (without need to define scala-library as a dependency) see http://davidb.github.io/scala-maven-plugin/compile-mojo.html#scalaVersion is is a full version `major.minor.bugfix`

`scala.compat.version` is the other property to used as part of the artifact's name see http://davidb.github.io/scala-maven-plugin/compile-mojo.html#scalaCompatVersion

So you should rename 
- `scala.version` into `scala.compat.version`
- `scala.minor.version` into `scala.version`

**Comment by slandelle** [comment]
> scala.version is used to define scala version (without need to define scala-library as a dependency) 

This feature is a bit surprising to me. Would IntelliJ properly work with such set up?

> is is a full version major.minor.bugfix

Surprisingly, it seems that `2.12` gets resolved at `2.12.0`.

**Comment by abhi0642** [comment]
While making a build for your project in any cloud environment. Try to change image from linux/unix to window or window to other. 
The operating system and image type should be the same to successfully build.

**Comment by indreshverma** [comment]
Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.8.0:compile failed: org.apache.commons.exec.ExecuteException

getting this exception while building the spark with 3.5.0 and 3.5.1 also
using java 17 and scala 2.13.13 tried to reduce the scala version also to 2.13.8 and scala-maven-plugin version to 3.4.0, 4.7.0 also but still getting the same issue .
Please help !!
